# .readthedocs.yaml

version: 2

# Указываем версию Python и способ установки зависимостей
python:
  version: 3.9  # Версия Python для сборки документации
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt  # Зависимости для документации

# Настройка Sphinx
sphinx:
  configuration: docs/conf.py  # Путь к конфигурационному файлу Sphinx

# Параметры сборки
build:
  os: ubuntu-22.04  # Операционная система
  tools:
    python: "3.9"  # Версия Python
