# .readthedocs.yaml

version: 2

# Параметры сборки
build:
  os: ubuntu-22.04  # Операционная система
  tools:
    python: "3.9"  # Указываем Python как инструмент сборки

# Настройка Sphinx
sphinx:
  configuration: docs/source/conf.py  # Путь к конфигурационному файлу Sphinx

python:
  install:
    - method: pip
      path: .
    - requirements: requirements.txt  # Указываем зависимости для документации