version: "3.9"
services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001" 
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  ml_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ml_service
    ports:
      - "8000:8000"
    environment:
      S3_ENDPOINT_URL: http://minio:9000
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin
      S3_BUCKET_NAME: mlops-bucket
    depends_on:
      - minio


volumes:
  minio_data:






