# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import model_service_pb2 as model__service__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in model_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ModelServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadData = channel.unary_unary(
                '/modelservice.ModelService/UploadData',
                request_serializer=model__service__pb2.UploadDataRequest.SerializeToString,
                response_deserializer=model__service__pb2.UploadDataResponse.FromString,
                _registered_method=True)
        self.TrainModel = channel.unary_unary(
                '/modelservice.ModelService/TrainModel',
                request_serializer=model__service__pb2.TrainModelRequest.SerializeToString,
                response_deserializer=model__service__pb2.TrainModelResponse.FromString,
                _registered_method=True)
        self.ListAvailableModels = channel.unary_unary(
                '/modelservice.ModelService/ListAvailableModels',
                request_serializer=model__service__pb2.Empty.SerializeToString,
                response_deserializer=model__service__pb2.ListAvailableModelsResponse.FromString,
                _registered_method=True)
        self.Predict = channel.unary_unary(
                '/modelservice.ModelService/Predict',
                request_serializer=model__service__pb2.PredictRequest.SerializeToString,
                response_deserializer=model__service__pb2.PredictResponse.FromString,
                _registered_method=True)
        self.DeleteModel = channel.unary_unary(
                '/modelservice.ModelService/DeleteModel',
                request_serializer=model__service__pb2.DeleteModelRequest.SerializeToString,
                response_deserializer=model__service__pb2.DeleteModelResponse.FromString,
                _registered_method=True)
        self.Status = channel.unary_unary(
                '/modelservice.ModelService/Status',
                request_serializer=model__service__pb2.Empty.SerializeToString,
                response_deserializer=model__service__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.ListTrainedModels = channel.unary_unary(
                '/modelservice.ModelService/ListTrainedModels',
                request_serializer=model__service__pb2.Empty.SerializeToString,
                response_deserializer=model__service__pb2.ListTrainedModelsResponse.FromString,
                _registered_method=True)
        self.GetPredictions = channel.unary_unary(
                '/modelservice.ModelService/GetPredictions',
                request_serializer=model__service__pb2.GetPredictionsRequest.SerializeToString,
                response_deserializer=model__service__pb2.GetPredictionsResponse.FromString,
                _registered_method=True)
        self.UpdateModel = channel.unary_unary(
                '/modelservice.ModelService/UpdateModel',
                request_serializer=model__service__pb2.UpdateModelRequest.SerializeToString,
                response_deserializer=model__service__pb2.UpdateModelResponse.FromString,
                _registered_method=True)


class ModelServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrainModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAvailableModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Predict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTrainedModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPredictions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadData': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadData,
                    request_deserializer=model__service__pb2.UploadDataRequest.FromString,
                    response_serializer=model__service__pb2.UploadDataResponse.SerializeToString,
            ),
            'TrainModel': grpc.unary_unary_rpc_method_handler(
                    servicer.TrainModel,
                    request_deserializer=model__service__pb2.TrainModelRequest.FromString,
                    response_serializer=model__service__pb2.TrainModelResponse.SerializeToString,
            ),
            'ListAvailableModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAvailableModels,
                    request_deserializer=model__service__pb2.Empty.FromString,
                    response_serializer=model__service__pb2.ListAvailableModelsResponse.SerializeToString,
            ),
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=model__service__pb2.PredictRequest.FromString,
                    response_serializer=model__service__pb2.PredictResponse.SerializeToString,
            ),
            'DeleteModel': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteModel,
                    request_deserializer=model__service__pb2.DeleteModelRequest.FromString,
                    response_serializer=model__service__pb2.DeleteModelResponse.SerializeToString,
            ),
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=model__service__pb2.Empty.FromString,
                    response_serializer=model__service__pb2.StatusResponse.SerializeToString,
            ),
            'ListTrainedModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTrainedModels,
                    request_deserializer=model__service__pb2.Empty.FromString,
                    response_serializer=model__service__pb2.ListTrainedModelsResponse.SerializeToString,
            ),
            'GetPredictions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPredictions,
                    request_deserializer=model__service__pb2.GetPredictionsRequest.FromString,
                    response_serializer=model__service__pb2.GetPredictionsResponse.SerializeToString,
            ),
            'UpdateModel': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateModel,
                    request_deserializer=model__service__pb2.UpdateModelRequest.FromString,
                    response_serializer=model__service__pb2.UpdateModelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'modelservice.ModelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('modelservice.ModelService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModelService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/modelservice.ModelService/UploadData',
            model__service__pb2.UploadDataRequest.SerializeToString,
            model__service__pb2.UploadDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TrainModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/modelservice.ModelService/TrainModel',
            model__service__pb2.TrainModelRequest.SerializeToString,
            model__service__pb2.TrainModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAvailableModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/modelservice.ModelService/ListAvailableModels',
            model__service__pb2.Empty.SerializeToString,
            model__service__pb2.ListAvailableModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/modelservice.ModelService/Predict',
            model__service__pb2.PredictRequest.SerializeToString,
            model__service__pb2.PredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/modelservice.ModelService/DeleteModel',
            model__service__pb2.DeleteModelRequest.SerializeToString,
            model__service__pb2.DeleteModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/modelservice.ModelService/Status',
            model__service__pb2.Empty.SerializeToString,
            model__service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTrainedModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/modelservice.ModelService/ListTrainedModels',
            model__service__pb2.Empty.SerializeToString,
            model__service__pb2.ListTrainedModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPredictions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/modelservice.ModelService/GetPredictions',
            model__service__pb2.GetPredictionsRequest.SerializeToString,
            model__service__pb2.GetPredictionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/modelservice.ModelService/UpdateModel',
            model__service__pb2.UpdateModelRequest.SerializeToString,
            model__service__pb2.UpdateModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
